#!/usr/bin/env bash
# System hardening for OpenClaw on Raspberry Pi 5 (Debian 13 Trixie)
# Run as root. Reports what it does at each step.

set -euo pipefail

log() { echo "[$(date '+%H:%M:%S')] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Must run as root (sudo $0)"

NFS_MOUNT=/mnt/openclaw
OPENCLAW_USER=openclaw
OPENCLAW_GROUP=openclaw

# ---------------------------------------------------------------------------
# 0. Safety net: schedule a reboot in 5 minutes in case the firewall locks
#    us out of SSH. Cancelled at the end of the script if all goes well.
# ---------------------------------------------------------------------------
log "Step 0: Scheduling safety-net reboot in 5 minutes (will be cancelled on success)..."
shutdown -r +5 "Safety-net reboot: firewall hardening in progress" 2>/dev/null || true
log "  Reboot scheduled. If SSH becomes unreachable, the Pi will reboot and restore access."

# ---------------------------------------------------------------------------
# 1. Create openclaw user and group
# ---------------------------------------------------------------------------
log "Step 1: Creating user/group '$OPENCLAW_USER'..."
if id "$OPENCLAW_USER" &>/dev/null; then
    log "  User already exists, skipping."
else
    groupadd --system "$OPENCLAW_GROUP"
    useradd  --system \
             --gid "$OPENCLAW_GROUP" \
             --no-create-home \
             --shell /usr/sbin/nologin \
             --comment "OpenClaw agent" \
             "$OPENCLAW_USER"
    log "  Created user '$OPENCLAW_USER'."
fi

# ---------------------------------------------------------------------------
# 2. Lock down the NFS mount directory
# ---------------------------------------------------------------------------
log "Step 2: Setting NFS mount permissions on $NFS_MOUNT..."
mountpoint -q "$NFS_MOUNT" || die "$NFS_MOUNT is not mounted. Check fstab and NFS server."
chown "$OPENCLAW_USER:$OPENCLAW_GROUP" "$NFS_MOUNT"
chmod 750 "$NFS_MOUNT"
log "  $NFS_MOUNT is now owned by $OPENCLAW_USER:$OPENCLAW_GROUP (mode 750)."

# ---------------------------------------------------------------------------
# 3. Firewall via nftables
#    Inbound:  allow SSH (22) only
#    Outbound: allow DNS (53), NTP (123), NFS (2049), api.anthropic.com (443)
#              allow responses to established connections
#              drop everything else
# ---------------------------------------------------------------------------
log "Step 3: Installing nftables..."
apt-get install -y --quiet nftables

ANTHROPIC_IP4=$(getent ahostsv4 api.anthropic.com | awk '{print $1; exit}')
ANTHROPIC_IP6=$(getent ahostsv6 api.anthropic.com | awk '{print $1; exit}')
[[ -n "$ANTHROPIC_IP4" || -n "$ANTHROPIC_IP6" ]] || die "Could not resolve api.anthropic.com — check DNS."
[[ -n "$ANTHROPIC_IP4" ]] && log "  api.anthropic.com IPv4: $ANTHROPIC_IP4"
[[ -n "$ANTHROPIC_IP6" ]] && log "  api.anthropic.com IPv6: $ANTHROPIC_IP6"

# Build Anthropic allowlist rules for whichever address families resolved
ANTHROPIC_RULES=""
[[ -n "$ANTHROPIC_IP4" ]] && ANTHROPIC_RULES+="        ip daddr $ANTHROPIC_IP4 tcp dport 443 accept"$'\n'
[[ -n "$ANTHROPIC_IP6" ]] && ANTHROPIC_RULES+="        ip6 daddr $ANTHROPIC_IP6 tcp dport 443 accept"$'\n'

NFS_SERVER_IP=10.0.0.214

log "Step 3: Writing nftables ruleset..."
cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# OpenClaw hardened firewall — generated by 01-harden.sh

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0; policy drop;

        # Allow loopback
        iif lo accept

        # Allow established/related
        ct state established,related accept

        # Allow SSH from any host on the local network
        tcp dport 22 accept

        # Drop everything else inbound
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy drop;

        # Allow loopback
        oif lo accept

        # Allow established/related
        ct state established,related accept

        # DNS (needed for hostname resolution)
        udp dport 53 accept
        tcp dport 53 accept

        # NTP (time sync)
        udp dport 123 accept

        # NFS to pi-nas
        ip daddr $NFS_SERVER_IP tcp dport 2049 accept
        ip daddr $NFS_SERVER_IP udp dport 2049 accept

        # Anthropic API (IPv4 and/or IPv6 as resolved at install time)
${ANTHROPIC_RULES}
        # Drop everything else outbound
    }
}
EOF

systemctl enable nftables
systemctl restart nftables
log "  nftables enabled and started."

# Verify SSH is still reachable (rule is in place)
nft list ruleset | grep -q "tcp dport 22" && log "  SSH rule confirmed in ruleset."

# ---------------------------------------------------------------------------
# 4. Harden fstab mount options
#    Add noexec,nosuid to the NFS mount so files there can't be executed
# ---------------------------------------------------------------------------
log "Step 4: Hardening fstab NFS mount options..."
FSTAB=/etc/fstab
if grep -q "noexec" "$FSTAB"; then
    log "  fstab already has noexec on NFS mount, skipping."
else
    sed -i 's|\(pi-nas:/export/openclaw.*nfs\s*\)\(defaults\)|\1defaults,noexec,nosuid|' "$FSTAB"
    log "  Added noexec,nosuid to NFS mount in fstab."
    log "  NOTE: Remount manually after confirming services are stable:"
    log "        mount -o remount $NFS_MOUNT"
fi

# ---------------------------------------------------------------------------
# 5. Cancel safety-net reboot and summarise
# ---------------------------------------------------------------------------
log "Step 5: Cancelling safety-net reboot (all steps succeeded)..."
shutdown -c 2>/dev/null || true
log "  Reboot cancelled."

log ""
log "Hardening complete. Summary:"
log "  User:     $OPENCLAW_USER (no shell, system account)"
log "  NFS mount: $NFS_MOUNT owned by $OPENCLAW_USER, mode 750, noexec,nosuid"
log "  Firewall: nftables active — inbound SSH only, outbound: DNS/NTP/NFS/$ANTHROPIC_IP:443"
log ""
log "Next step: run 'nft list ruleset' and 'id openclaw' to verify, then report back."
